import { Layout } from "antd";
import Head from "next/head";

const { Header, Footer, Sider, Content } = Layout;

const ForumLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header>Header</Header>
        <Layout>
          <Sider>Sider</Sider>
          <Layout>
            <Sider>Sider</Sider>
            <Content>Content</Content>
          </Layout>
        </Layout>
        <Footer>Footer</Footer>
      </Layout>
    </>
  );
};

export default ForumLayout;
